dataset_name: bimanual/ur_example  # was actually name but seems wrong in the code
type: single
shards_dir: /cluster/home/sage/RDT2/data_shards/shards
kwargs:
  instruction_path: /cluster/home/sage/RDT2/data_shards/instructions.json
  normalizer_path: /cluster/home/sage/RDT2/normalizer/umi_normalizer_wo_downsample_indentity_rot.pt # download from http://ml.cs.tsinghua.edu.cn/~lingxuan/rdt2/umi_normalizer_wo_downsample_indentity_rot.pt